name: Flutter Build APK

on:
  push:
    branches:
      - main  # Corre solo cuando haces push en la rama main

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Ajusta aquí a tu versión exacta si cambia

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Release Mode)
        run: flutter build apk --release --split-per-abi

      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: APKs-Releases
          path: build/app/outputs/flutter-apk/*.apk
